<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="10.0.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Hangfire.InMemory" Version="1.0.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
        <PackageReference Include="NSubstitute" Version="5.3.0" />
        <PackageReference Include="TestableIO.System.IO.Abstractions.TestingHelpers" Version="22.1.1" />
        <PackageReference Include="xunit" Version="2.9.3"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Fathom.Common\Fathom.Common.csproj" />
      <ProjectReference Include="..\Fathom.Database\Fathom.Database.csproj" />
      <ProjectReference Include="..\Fathom.Services\Fathom.Services.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\Fathom.Server\config\appsettings.json">
        <Link>config\appsettings.json</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
