export enum WikiLink {
  Customize = 'https://wiki.fathomreader.com/guides/features/customization',
  CustomizeExternalSource = 'https://wiki.fathomreader.com/guides/features/customization#external-source',
  ReadingLists = 'https://wiki.fathomreader.com/guides/features/readinglists',
  Collections = 'https://wiki.fathomreader.com/guides/features/collections',
  SeriesRelationships = 'https://wiki.fathomreader.com/guides/features/relationships',
  Bookmarks = 'https://wiki.fathomreader.com/guides/features/bookmarks',
  DataCollection = 'https://wiki.fathomreader.com/troubleshooting/faq#q-does-kavita-collect-any-data-on-me',
  MediaIssues = 'https://wiki.fathomreader.com/guides/admin-settings/mediaissues/',
  KavitaPlusDiscordId = 'https://wiki.fathomreader.com/guides/admin-settings/kavita+#discord-id',
  KavitaPlus = 'https://wiki.fathomreader.com/kavita+',
  KavitaPlusFAQ = 'https://wiki.fathomreader.com/kavita+/faq',
  ReadingListCBL = 'https://wiki.fathomreader.com/guides/features/readinglists#creating-a-reading-list-via-cbl',
  Donation = 'https://wiki.fathomreader.com/donating',
  Updating = 'https://wiki.fathomreader.com/guides/updating',
  ManagingFiles = 'https://wiki.fathomreader.com/guides/scanner/managefiles',
  Scanner = 'https://wiki.fathomreader.com/guides/scanner',
  ScannerExclude = 'https://wiki.fathomreader.com/guides/admin-settings/libraries#exclude-patterns',
  Library = 'https://wiki.fathomreader.com/guides/admin-settings/libraries',
  UpdateNative = 'https://wiki.fathomreader.com/installation/native/',
  UpdateDocker = 'https://wiki.fathomreader.com/installation/docker/',
  OpdsClients = 'https://wiki.fathomreader.com/guides/features/opds/#opds-capable-clients',
  Guides = 'https://wiki.fathomreader.com/guides',
  ReadingProfiles = "https://wiki.fathomreader.com/guides/user-settings/reading-profiles/",
  EpubFontManager = "https://wiki.fathomreader.com/guides/epub-fonts/",
  CblImportModal = 'https://wiki.fathomreader.com/guides/features/cbl-import/'
}
